- title: "💡 P13 Discussion Group"
  description: "Private group for sharing ideas in IT between Vietnamese friends at University Sorbonne Paris Nord"
  source: "https://github.com/dinhanhthi/P13-discuss-group"
# - title: "🧠 deeplearning.ai notes"
#   description: "My handwriting-notes & codes for the courses of deeplearning.ai taught by Andrew NG on Coursera."
#   source: "https://github.com/dinhanhthi/deeplearning.ai-notes"
# - title: 🍓 dataquest aio
#   description: "All python notebooks & takeaways & my-way of descriptions for missions and guided projects on Dataquest."
#   source: https://github.com/dinhanhthi/dataquest-aio
- title: 📊 data science learning
  description: All of courses, assignments, exercises, mini-projects and books that I've done so far in the process of learning by myself Machine Learning and Data Science.
  source: https://github.com/dinhanhthi/data-science-learning
- title: 🎯 betterexplained vn
  description: "Vietnamese translation of Kalid Azad's articles published on BetterExplained. This is a very useful website for ones who want to understand intuitively about Math."
  source: https://github.com/math2it/BetterExplained-vn-translation
  url: https://betterexplained.math2it.com/
- title: 🍒 simple perso
  description: A simple and beautiful personal jekyll theme.
  source: https://github.com/dinhanhthi/simple-perso
  url: https://dinhanhthi.github.io/simple-perso/
- title: ⭐ dinhanhthi.com
  description: "Source code of my personal website."
  source: https://github.com/dinhanhthi/dinhanhthi.com
  url: http://dinhanhthi.com
- title: 📓 raw-note
  description: "Source code of my personal raw notes. Different from <em>better-note</em>, I use this website for quickly capturing ideas."
  source: https://github.com/dinhanhthi/raw-note
  url: http://rawnote.dinhanhthi.com
- title: ☕ cafe in hcm
  description: "A capstone project for the course \"Applied Data Science Capstone\" by IBM on Coursera. Setting up a café in Ho Chi Minh city."
  source: https://github.com/dinhanhthi/cafe-in-hcm
  url: https://note.dinhanhthi.com/setting-up-a-cafe-in-hcmc
- title: 🎨 ThiThesisTemp
  description: A simple beautiful LaTeX theme for books, thesis.
  source: https://github.com/dinhanhthi/ThiThesisTemp
- title: 🐘 math2itwp
  description: A beautiful Wordpress theme based on Bootstrap 4 with different layouts of posts.
  source: https://github.com/dinhanhthi/math2itwp
  url: https://math2it.com
- title: 📝 notethteme
  description: An AIO Jekyll theme designed for the purpose of taking notes.
  url: https://dinhanhthi.github.io/NoteTheme/
  source: https://github.com/dinhanhthi/NoteTheme
- title: 🔥 math2it.com
  description: A Vietnamese site for intuitive knowledge (Maths, Education and Technology).
  source: https://github.com/dinhanhthi/math2itwp
  url: http://math2it.com
- title: 🎲 Math2IT Group
  description: A Vietnamese community about math, education and technology.
  url: https://www.facebook.com/groups/math2it/
- title: 🚀 TaniaJekyll
  description: A beautiful personal Jekyll theme with different layouts of posts designed, based on Bootstrap 4 & Jekyll.
  url: https://dinhanhthi.github.io/TaniaJekyll
  source: https://github.com/dinhanhthi/TaniaJekyll
- title: 🔢 NXFEM
  source: https://github.com/dinhanhthi/nxfem
  description: A Matlab library for Nitsche - Extended Finite Element Method.

